name: "Publish to ghcr.io"
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          cat >> "$GITHUB_ENV" <<EOF
          latest=ghcr.io/${{ github.repository }}:latest
          current=ghcr.io/${{ github.repository }}:$(git rev-parse --short ${{ github.sha }})
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.latest }},${{ env.current }}
          cache-from: type=gha
          cache-to: type=gha,mode=max